Repository daniel-melanson/UMass-CICS-Discord-Bot, pull requests merged in 2020-05, with the labels that each got.

#2 Add info command, license project as AGPLv3
  LICENSE
  package.json
  src/commands/misc/source-command.js
Labels: enhancement

#3 Add .gitignore, package-lock.json, and math classes functionality
  .gitignore
  package-lock.json
  src/commands/classes/class-command.js
  src/course-information-math.js
Labels: enhancement

#6 Cleanup math courses and add documentation
  src/course-information-math.js
Labels: documentation

#9 Adds new RAP roles and math classes to the list command
  src/commands/classes/class-list-command.js
  src/course-information-math.js
  src/util.js
Labels: enhancement

#16 Add instructions for removing roles
  src/commands/roles/role-command.js
  src/commands/roles/roles-command.js
Labels: documentation, enhancement
